# 1.You’re a programmer working for Copeland’s Corporate Company. At this company, each employee’s user name is generated by taking the first five letters of their last name.
# A new employee, Rodrigo Villanueva, is starting today and you need to create his account. His first_name and last_name are stored as strings in script.py.
# Create a variable new_account by slicing the first five letters of his last_name.

# 2.Temporary passwords for new employees are also generated from their last names.
# Create a variable called temp_password by creating a slice out of the third through sixth letters of last_name.Your string should have a total of 4 characters.

first_name = "Rodrigo"

last_name = "Villanueva"
  
new_account = last_name[:5]
temp_password = last_name[2:6]
